# Generated by Django 2.0.13 on 2020-07-03 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200703_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default=datetime.datetime(2020, 7, 3, 19, 2, 26, 489906, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
