# Generated by Django 2.0.13 on 2020-07-04 09:04

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2020, 7, 4)),
        ),
    ]
