# Generated by Django 2.0.13 on 2020-07-03 18:09

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='register',
            field=django_jalali.db.models.jDateField(default=datetime.datetime(2020, 7, 3, 18, 9, 2, 860173, tzinfo=utc), verbose_name=datetime.datetime(2020, 7, 3, 18, 8, 53, 253678, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
