# Generated by Django 2.0.13 on 2020-07-04 09:24

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20200704_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register',
            field=django_jalali.db.models.jDateField(verbose_name=datetime.datetime(2020, 7, 4, 9, 24, 16, 916788, tzinfo=utc)),
        ),
    ]
