# Generated by Django 2.0.13 on 2020-07-04 14:06

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20200704_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='register',
            field=django_jalali.db.models.jDateField(verbose_name=datetime.datetime(2020, 7, 4, 14, 6, 20, 298472, tzinfo=utc)),
        ),
    ]
