# Generated by Django 2.0.13 on 2020-07-03 22:17

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='upload/image')),
                ('file', models.FileField(blank=True, upload_to='upload/file')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('organ', models.CharField(choices=[('enteshar', 'Enteshar'), ('fanni', 'Fanni'), ('bargozari', 'Bargozari')], max_length=100)),
            ],
        ),
    ]
