# Generated by Django 2.0.13 on 2020-07-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='name',
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='requested_by_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='upload',
            name='requested_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='upload/file'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='upload/image'),
        ),
    ]
