# Generated by Django 2.0.13 on 2020-07-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_upload_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='requested_by_id',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='requested_by_name',
        ),
    ]
